image:
  repository: aemunoz87/power-outage-schedule
  tag: latest

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
